CREATE DATABASE CT180011
GO
USE CT180011
Go
CREATE TABLE KIENTRUCSU
(
	MSKTS NVARCHAR(5) PRIMARY KEY,
	HOTENKTS NVARCHAR(40),
	NGAYSINH DATE,
	PHAI NVARCHAR(5), 
	NOITN NVARCHAR(30),
	DIACHIKTS NVARCHAR(50),
)
Go
CREATE TABLE CHUTHAU
(
	MSCT NVARCHAR(10) PRIMARY KEY,
	TENTHAU NVARCHAR(40),
	DIENTHOAI INT,
	DIACHITHAU NVARCHAR(50)
)
Go
CREATE TABLE CHUNHAN
(
	MSCH NVARCHAR(10) PRIMARY KEY,
	TENCHU NVARCHAR(40),
	PHAI NVARCHAR(5),
	DIACHICHU NVARCHAR(50) 
)
CREATE TABLE CONGNHAN
(
	MSCN NVARCHAR(10) PRIMARY KEY,
	HOTENCN NVARCHAR(40),
	NGAYSINH DATE,
	PHAI NVARCHAR(5),
	CHUYENMON NVARCHAR(20)
)
GO
CREATE TABLE CONGTRINH
(
	STTCT NVARCHAR(5) PRIMARY KEY,
	TENCT NVARCHAR(40),
	DIACHICT NVARCHAR(50),
	TINHTHANH NVARCHAR(20),
	KINHPHI INT,
	MSCH NVARCHAR(10) REFERENCES dbo.CHUNHAN(MSCH),
	MSCT NVARCHAR(10) REFERENCES dbo.CHUTHAU(MSCT),
	NGAYBD DATE,
)
Go
CREATE TABLE THAMGIA
(
	MSCN NVARCHAR(10) REFERENCES dbo.CONGNHAN(MSCN),
	STTCT NVARCHAR(5) REFERENCES dbo.CONGTRINH(STTCT),
	NGAYTG DATE,
	SONGAY INT
	PRIMARY KEY(MSCN,STTCT)
)
Go
CREATE TABLE THIETKE
(
	MSKTS NVARCHAR(5) REFERENCES dbo.KIENTRUCSU(MSKTS),
	STTCT NVARCHAR(5) REFERENCES dbo.CONGTRINH(STTCT),
	THULAO SMALLINT,
	PRIMARY KEY(MSKTS,STTCT)
)
Go

INSERT INTO KIENTRUCSU
VALUES('K1','Nguyen Ngoc Anh','19690523','NAM','Can Tho','21 le duan,tp hcm')

INSERT INTO CHUTHAU
VALUES('THAU1','Hong Xuan Truong','8617434371','23 tran hung dao,vinh long')

INSERT INTO CHUNHAN
VALUES('CHU1','Hong Xuan Truong','nam','23 tran hung dao,vinh long')

INSERT INTO CONGNHAN
VALUES('CN1','Nguyen Thi Su','19860102','nam','han')

INSERT INTO CONGTRINH
VALUES('CT1','Khach san quoc te','101 le lai','can tho','500','CHU1','THAU1','19941218')

INSERT INTO THAMGIA
VALUES('CN11','CT9','20180519','73')

INSERT INTO CHUNHAN
VALUES('K2','CT8',72)
